name: Deploy static files to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Assignment3AzureCoursePlan'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_312A794C3C1848DC83F75E40A241DDBE }}
          package: .

      - name: Run smoke test
        run: |
          echo "Running smoke test..."
          $response = curl -s -w "%{http_code}" -o response.txt "https://assigment3cloud.azurewebsites.net/api/Smoketest-Dan?code=${{ secrets.FUNCTION_KEY }}"
          echo "Smoke test response code: $response"
          echo "Response body: $(Get-Content response.txt)"
          if ($response -eq 200) {
            echo "Smoke test passed: 200 OK"
          } else {
            echo "Smoke test failed: $response"
            exit 1
          }
