name: Deploy static files to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Assignment3AzureCoursePlan'  # Replace with your Azure Web App name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_312A794C3C1848DC83F75E40A241DDBE }}  # Secret for Azure publish profile
          package: .  # Use the current directory where the static files are located

      - name: Run smoke test
        run: |
          echo "Running smoke test..."
          FUNCTION_KEY="${{ secrets.FUNCTION_KEY }}"  # Get function key from secret
          RESPONSE=$(curl -s -w "%{http_code}" -o /dev/null "https://assigment3cloud.azurewebsites.net/api/Smoketest-Dan?code=$FUNCTION_KEY")
          echo "Response code: $RESPONSE"
          if [ "$RESPONSE" -eq 200 ]; then
            echo "Smoke test passed: 200 OK"
          else
            echo "Smoke test failed: HTTP status $RESPONSE"
            exit 1
          fi
